### ISSUE TITLE
Multiple  errors while launching igt_ignition.launch.py

### ISSUE THREAD

**Issue by Harshavardhan341** [TechnoYantra/ros2-igt#3] opened 2021-07-14 18:56 UTC
Hi,
I am getting multiple errors and warnings while launching the given ig_ignition.launch.py with the bridge. Also the differential drive type bot isn't spawning properly as the castor wheel is not fixed to the chassis. The simulation is continuously pausing and playing. I am a novice in ROS2 and Ignition, hence, it would be of great help if you helped me in resolving these issues.
Thanks.

> [ign gazebo-1] Warning [parser.cc:867] XML Attribute[frame] in element[pose] not defined in SDF, ignoring.
[ign gazebo-1] Warning [parser.cc:867] XML Attribute[frame] in element[pose] not defined in SDF, ignoring.
[ign gazebo-1] Warning [parser.cc:867] XML Attribute[frame] in element[pose] not defined in SDF, ignoring.
[ign gazebo-1] Warning [parser.cc:867] XML Attribute[frame] in element[pose] not defined in SDF, ignoring.
[ign gazebo-1] Warning [parser.cc:867] XML Attribute[frame] in element[pose] not defined in SDF, ignoring.
[ign gazebo-1] Warning [parser.cc:867] XML Attribute[frame] in element[pose] not defined in SDF, ignoring.
[ign gazebo-1] Warning [parser.cc:867] XML Attribute[frame] in element[pose] not defined in SDF, ignoring.
[ign gazebo-1] Warning [parser.cc:867] XML Attribute[frame] in element[pose] not defined in SDF, ignoring.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:657] [QT] file::/Gazebo/GazeboDrawer.qml:178:3: QML Dialog: Binding loop detected for property "implicitHeight"
[ign gazebo-1] [GUI] [Wrn] [Application.cc:657] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
[ign gazebo-1] [GUI] [Wrn] [Application.cc:657] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain")
[ign gazebo-1] [GUI] [Wrn] [Application.cc:657] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
[ign gazebo-1] [GUI] [Wrn] [Application.cc:657] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain")
[ign gazebo-1] [GUI] [Wrn] [Application.cc:657] [QT] file::/Gazebo/GazeboDrawer.qml:178:3: QML Dialog: Binding loop detected for property "implicitHeight"
[ign gazebo-1] [Wrn] [SimulationRunner.cc:583] Found additional publishers on /stats, using namespaced stats topic only
[ign gazebo-1] [Wrn] [SimulationRunner.cc:616] Found additional publishers on /clock, using namespaced clock topic only
[ign gazebo-1] [Err] [SystemPaths.cc:362] Unable to find file with URI [model:///table_marble/meshes/table_lightmap.dae]
[ign gazebo-1] [Err] [SystemPaths.cc:449] Could not resolve file [model:///table_marble/meshes/table_lightmap.dae]
[ign gazebo-1] [Err] [MeshManager.cc:172] Unable to find file[model:///table_marble/meshes/table_lightmap.dae]
[ign gazebo-1] [Wrn] [Physics.cc:831] Failed to load mesh from [model:///table_marble/meshes/table_lightmap.dae].
[ign gazebo-1] [GUI] [Wrn] [Application.cc:657] [QT] file::/WorldControl/WorldControl.qml:88:3: QML RoundButton: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [WorldControl.cc:108] Ignoring service [/world/station/control], world name different from [default]. Fix or remove your <service> tag.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:657] [QT] file::/WorldControl/WorldControl.qml:88:3: QML RoundButton: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [WorldControl.cc:176] Ignoring topic [/world/station/stats], world name different from [default]. Fix or remove your <stats_topic> tag.
[ign gazebo-1] [GUI] [Wrn] [WorldStats.cc:112] Ignoring topic [/world/station/stats], world name different from [default]. Fix or remove your <topic> tag.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:657] [QT] file::/ImageDisplay/ImageDisplay.qml:89:5: QML Image: Invalid image provider: image://plugin82233imagedisplay/6t47q
[ign gazebo-1] [GUI] [Wrn] [Application.cc:657] [QT] file::/ImageDisplay/ImageDisplay.qml:89:5: QML Image: Invalid image provider: image://plugin54887imagedisplay/vrneq
[ign gazebo-1] [GUI] [Err] [SystemPaths.cc:362] Unable to find file with URI [model://table_marble/meshes/table_lightmap.dae]
[ign gazebo-1] [GUI] [Err] [SystemPaths.cc:449] Could not resolve file [model://table_marble/meshes/table_lightmap.dae]
[ign gazebo-1] [GUI] [Err] [MeshManager.cc:172] Unable to find file[model://table_marble/meshes/table_lightmap.dae]
[ign gazebo-1] [GUI] [Err] [MeshDescriptor.cc:56] Mesh manager can't find mesh named [model://table_marble/meshes/table_lightmap.dae]
[ign gazebo-1] [GUI] [Err] [Ogre2MeshFactory.cc:431] Cannot load null mesh [model://table_marble/meshes/table_lightmap.dae]
[ign gazebo-1] [GUI] [Err] [Ogre2MeshFactory.cc:72] Failed to get Ogre item for [model://table_marble/meshes/table_lightmap.dae]
[ign gazebo-1] [GUI] [Err] [SceneManager.cc:341] Failed to load geometry for visual: visual
![Screenshot from 2021-07-15 00-14-40](https://user-images.githubusercontent.com/55760311/125677027-e62c2fc1-eb4f-4dbc-b2ed-c179fa60f2e7.png)

**Comment by jasmeet0915** [comment] 2021-07-15 13:48
Hi @Harshavardhan341, 
Thank you for reporting the issue. The caster wheel issue was not caused by the caster not being fixed to the chassis but instead it was caused by an offset in the joint pose but should be resolved in the [latest commit](https://github.com/TechnoYantra/ros2-igt/commit/82fa2419ec18d5a947a02e9f52d4bbebb94a6d20).

The following and all other related errors are caused due to a missing `table_lightmap.dae` mesh file which got missed during the migration from classic gazebo's world file. We plan to resolve these issue soon by further cleaning up of the `lab.sdf` file and loading all such models from [ignition fuel](https://app.ignitionrobotics.org/fuel/models). 
```bash
[ign gazebo-1] [GUI] [Err] [MeshDescriptor.cc:56] Mesh manager can't find mesh named [model://table_marble/meshes/table_lightmap.dae]
```
These errors should not have any direct effects on the simulation as of now. 

As for the play/pause you are facing, I am not sure what could be causing the issue as it works fine on my end. It would be helpful if you could provide more details regarding this like the version of ignition you are using etc.
Have you noticed any particular stimuli that you think might be causing the play/pause that I could use to recreate the issue or is it happening at random?

**Comment by Harshavardhan341** [comment] 2021-07-15 15:28
Hi @jasmeet0915, 
Thank you for resolving my issue. After pulling the latest version and building the packages, the play/pause issue seems to have disappeared as well.

**Comment by jasmeet0915** [comment] 2021-07-15 20:45
Glad to help! I am closing this issue.

**Closed** 2021-07-15 20:45 UTC
Labels: bug, help wanted
